//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDETools {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceCustomUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCustomUI() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CDETools.ResourceCustomUI", typeof(ResourceCustomUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;customUI xmlns=&apos;http://schemas.microsoft.com/office/2006/01/customui&apos; loadImage=&apos;LoadImage&apos;  onLoad=&apos;ribbonLoaded&apos;&gt;
        ///    &lt;!-- 在 [XML]中被定义为 空白(whitespace)字符：空格 (&amp;#x0020;) Tab (&amp;#x0009;) 回车 (&amp;#x000D;) 换行 (&amp;#x000A;)--&gt;
        ///  &lt;ribbon startFromScratch=&quot;false&quot;&gt;
        ///    &lt;tabs&gt;
        ///      &lt;tab id=&apos;CustomTab&apos; label=&apos;CDE Tools&apos; insertAfterMso=&quot;TabHome&quot;&gt;
        ///        &lt;group id=&apos;uploadGroup&apos; label=&apos;Upload Template&apos;&gt;
        ///		 &lt;menu id=&quot;uploadMenu&quot; label=&quot;Upload&quot; imageMso=&quot;ReviewCompareMenu&quot; size=&quot;large&quot;&gt;
        ///            &lt;button id=&quot;uploadxm [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CustomUI12cn {
            get {
                return ResourceManager.GetString("CustomUI12cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;customUI xmlns=&apos;http://schemas.microsoft.com/office/2006/01/customui&apos; loadImage=&apos;LoadImage&apos;  onLoad=&apos;ribbonLoaded&apos;&gt;
        ///    &lt;!-- 在 [XML]中被定义为 空白(whitespace)字符：空格 (&amp;#x0020;) Tab (&amp;#x0009;) 回车 (&amp;#x000D;) 换行 (&amp;#x000A;)--&gt;
        ///  &lt;ribbon startFromScratch=&quot;false&quot;&gt;
        ///    &lt;tabs&gt;
        ///      &lt;tab id=&apos;CustomTab&apos; label=&apos;CDE Tools&apos; insertAfterMso=&quot;TabHome&quot;&gt;
        ///        &lt;group id=&apos;uploadGroup&apos; label=&apos;Upload Template&apos;&gt;
        ///		 &lt;menu id=&quot;uploadMenu&quot; label=&quot;Upload&quot; imageMso=&quot;ReviewCompareMenu&quot; size=&quot;large&quot;&gt;
        ///            &lt;button id=&quot;uploadxm [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CustomUI12en {
            get {
                return ResourceManager.GetString("CustomUI12en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;customUI xmlns=&apos;http://schemas.microsoft.com/office/2009/07/customui&apos; loadImage=&apos;LoadImage&apos;  onLoad=&apos;ribbonLoaded&apos;&gt;
        ///  &lt;!-- 在 [XML]中被定义为 空白(whitespace)字符：空格 (&amp;#x0020;) Tab (&amp;#x0009;) 回车 (&amp;#x000D;) 换行 (&amp;#x000A;)--&gt;
        ///  &lt;ribbon startFromScratch=&quot;false&quot;&gt;
        ///    &lt;tabs&gt;
        ///      &lt;tab id=&apos;CustomTab&apos; label=&apos;CDE Tools&apos; insertAfterMso=&quot;TabHome&quot;&gt;
        ///        &lt;group id=&apos;uploadGroup&apos; label=&apos;Upload Template&apos;&gt;
        ///		 &lt;menu id=&quot;uploadMenu&quot; label=&quot;Upload&quot; imageMso=&quot;ReviewCompareMenu&quot; size=&quot;large&quot;&gt;
        ///            &lt;button id=&quot;uploadxml&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CustomUI14cn {
            get {
                return ResourceManager.GetString("CustomUI14cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;customUI xmlns=&apos;http://schemas.microsoft.com/office/2009/07/customui&apos; loadImage=&apos;LoadImage&apos;  onLoad=&apos;ribbonLoaded&apos;&gt;
        ///  &lt;!-- 在 [XML]中被定义为 空白(whitespace)字符：空格 (&amp;#x0020;) Tab (&amp;#x0009;) 回车 (&amp;#x000D;) 换行 (&amp;#x000A;)--&gt;
        ///  &lt;ribbon startFromScratch=&quot;false&quot;&gt;
        ///    &lt;tabs&gt;
        ///      &lt;tab id=&apos;CustomTab&apos; label=&apos;CDE Tools&apos; insertAfterMso=&quot;TabHome&quot;&gt;
        ///        &lt;group id=&apos;uploadGroup&apos; label=&apos;Upload Template&apos;&gt;
        ///		 &lt;menu id=&quot;uploadMenu&quot; label=&quot;Upload&quot; imageMso=&quot;ReviewCompareMenu&quot; size=&quot;large&quot;&gt;
        ///            &lt;button id=&quot;uploadxml&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CustomUI14en {
            get {
                return ResourceManager.GetString("CustomUI14en", resourceCulture);
            }
        }
    }
}
